import type { ModelAssetCandidate } from './types'
import { buttonPins, connectorPins, i2cModulePins, ledPins, threePinModulePins, twoLeadPins } from './pins'

const kicadRaw = (path: string) => `https://raw.githubusercontent.com/KiCad/kicad-packages3D/master/${path}`
const sparkfunRaw = (path: string) => `https://raw.githubusercontent.com/sparkfun/SparkFun-KiCad-Libraries/main/${path}`
const antmicroRaw = (path: string) => `https://raw.githubusercontent.com/antmicro/hardware-components/main/gltf-models/${path}`

function kicad(path: string, partial: Omit<ModelAssetCandidate, 'sourceId' | 'sourceUrl' | 'assetUrl' | 'licenseName' | 'licenseUrl' | 'licenseUse' | 'attribution' | 'format' | 'modelFileName'> & {
  format?: 'step' | 'wrl'
  modelFileName?: string
}): ModelAssetCandidate {
  const format = partial.format ?? (path.toLowerCase().endsWith('.wrl') ? 'wrl' : 'step')
  return {
    ...partial,
    sourceId: 'kicad-packages3d',
    sourceUrl: 'https://github.com/KiCad/kicad-packages3D',
    assetUrl: kicadRaw(path),
    licenseName: 'CC-BY-SA 4.0 with KiCad library exception',
    licenseUrl: 'https://www.kicad.org/libraries/license/',
    licenseUse: 'bundled-ok',
    attribution: 'KiCad Libraries contributors',
    format,
    modelFileName: partial.modelFileName ?? `${partial.componentId}.${format}`,
    suggestedScale: partial.suggestedScale ?? 0.001,
  }
}

function sparkfun(path: string, partial: Omit<ModelAssetCandidate, 'sourceId' | 'sourceUrl' | 'assetUrl' | 'licenseName' | 'licenseUrl' | 'licenseUse' | 'attribution' | 'format' | 'modelFileName'> & {
  format?: 'step' | 'stp'
  modelFileName?: string
}): ModelAssetCandidate {
  const format = partial.format ?? (path.toLowerCase().endsWith('.stp') ? 'stp' : 'step')
  return {
    ...partial,
    sourceId: 'sparkfun-kicad-libraries',
    sourceUrl: 'https://github.com/sparkfun/SparkFun-KiCad-Libraries',
    assetUrl: sparkfunRaw(path),
    licenseName: 'CC-BY 4.0',
    licenseUrl: 'https://github.com/sparkfun/SparkFun-KiCad-Libraries#license',
    licenseUse: 'bundled-ok',
    attribution: 'SparkFun Electronics',
    format,
    modelFileName: partial.modelFileName ?? `${partial.componentId}.${format}`,
    suggestedScale: partial.suggestedScale ?? 0.001,
  }
}

function antmicro(path: string, partial: Omit<ModelAssetCandidate, 'sourceId' | 'sourceUrl' | 'assetUrl' | 'licenseName' | 'licenseUrl' | 'licenseUse' | 'attribution' | 'format' | 'modelFileName'> & {
  modelFileName?: string
}): ModelAssetCandidate {
  return {
    ...partial,
    sourceId: 'antmicro-hardware-components',
    sourceUrl: 'https://github.com/antmicro/hardware-components',
    assetUrl: antmicroRaw(path),
    licenseName: 'Apache-2.0',
    licenseUrl: 'https://github.com/antmicro/hardware-components/blob/main/LICENSE',
    licenseUse: 'bundled-ok',
    attribution: 'Antmicro',
    format: 'gltf',
    modelFileName: partial.modelFileName ?? `${partial.componentId}.gltf`,
    suggestedScale: partial.suggestedScale ?? 0.001,
  }
}

const beginnerWarnings = [
  'Review physical pin labels against your real part before wiring hardware.',
  'Imported visual models do not prove electrical safety.',
]

export const STARTER_MODEL_ASSETS: ModelAssetCandidate[] = [
  kicad('LED_THT.3dshapes/LED_D5.0mm.step', {
    id: 'kicad-led-5mm',
    label: '5mm through-hole LED',
    componentId: 'model-led-5mm-kicad',
    componentName: '5mm LED model',
    description: 'Recognizable round 5mm LED body for beginner LED projects.',
    family: 'indicator',
    keywords: ['led', '5mm', 'red led', 'light', 'indicator', 'through hole'],
    exactness: 'generic',
    category: 'actuator',
    schematicSymbol: 'led',
    defaultPins: ledPins,
    beginnerNotes: ['Use with a current-limiting resistor such as 220 ohm.'],
    reviewWarnings: beginnerWarnings,
  }),
  kicad('LED_THT.3dshapes/LED_D5.0mm-4_RGB.step', {
    id: 'kicad-rgb-led-5mm',
    label: '5mm RGB LED',
    componentId: 'model-rgb-led-5mm-kicad',
    componentName: '5mm RGB LED model',
    description: 'Four-pin RGB LED package for color projects.',
    family: 'indicator',
    keywords: ['rgb led', 'led', 'color', '5mm', 'indicator'],
    exactness: 'generic',
    category: 'actuator',
    schematicSymbol: 'led',
    defaultPins: connectorPins(4),
    beginnerNotes: ['RGB LEDs can be common-anode or common-cathode; verify the longest lead and datasheet.'],
    reviewWarnings: [...beginnerWarnings, 'Pin order depends on the actual RGB LED part.'],
  }),
  sparkfun('3dmodels/LED.3dshapes/LED_PTH_5mm_Red.step', {
    id: 'sparkfun-led-5mm-red',
    label: 'SparkFun 5mm red LED',
    componentId: 'model-led-5mm-red-sparkfun',
    componentName: 'SparkFun 5mm Red LED model',
    description: 'SparkFun-style red 5mm through-hole LED model.',
    family: 'indicator',
    keywords: ['led', 'red led', '5mm', 'sparkfun', 'through hole'],
    exactness: 'generic',
    category: 'actuator',
    schematicSymbol: 'led',
    defaultPins: ledPins,
    beginnerNotes: ['Good visual match for starter kit red LEDs.'],
    reviewWarnings: beginnerWarnings,
  }),
  sparkfun('3dmodels/Resistor.3dshapes/R_0.25W_D1.8_L3.2_Pitch-7.5_Spacing-0_Beige.stp', {
    id: 'sparkfun-axial-resistor',
    label: 'Axial resistor',
    componentId: 'model-axial-resistor-sparkfun',
    componentName: 'Axial Resistor model',
    description: 'Through-hole beige resistor body for current limiting and pull-ups.',
    family: 'resistor',
    keywords: ['resistor', '220 ohm', '330 ohm', '1k', '4.7k', '10k', 'axial'],
    exactness: 'generic',
    category: 'misc',
    schematicSymbol: 'resistor',
    defaultPins: twoLeadPins(0.0075),
    beginnerNotes: ['Use color bands or a multimeter to confirm the actual resistance value.'],
    reviewWarnings: [...beginnerWarnings, 'Visual model does not encode resistor value.'],
  }),
  kicad('Capacitor_THT.3dshapes/C_Disc_D5.0mm_W2.5mm_P5.00mm.step', {
    id: 'kicad-ceramic-capacitor',
    label: 'Ceramic disc capacitor',
    componentId: 'model-ceramic-capacitor-kicad',
    componentName: 'Ceramic Disc Capacitor model',
    description: 'Small two-lead capacitor body for decoupling examples.',
    family: 'capacitor',
    keywords: ['capacitor', 'ceramic', '100nf', '0.1uf', 'decoupling'],
    exactness: 'generic',
    category: 'misc',
    schematicSymbol: 'capacitor',
    defaultPins: twoLeadPins(0.005),
    beginnerNotes: ['Ceramic capacitors are usually not polarized.'],
    reviewWarnings: [...beginnerWarnings, 'Visual model does not encode capacitance value.'],
  }),
  kicad('Capacitor_THT.3dshapes/CP_Radial_D6.3mm_P2.50mm.step', {
    id: 'kicad-electrolytic-capacitor',
    label: 'Radial electrolytic capacitor',
    componentId: 'model-electrolytic-capacitor-kicad',
    componentName: 'Electrolytic Capacitor model',
    description: 'Polarized can-style capacitor with two radial leads.',
    family: 'capacitor',
    keywords: ['capacitor', 'electrolytic', '10uf', '100uf', 'polarized'],
    exactness: 'generic',
    category: 'misc',
    schematicSymbol: 'capacitor',
    defaultPins: [
      { id: 'positive', label: '+', type: 'power_in', position: [-0.00125, -0.004, 0], normal: [0, -1, 0] },
      { id: 'negative', label: '-', type: 'ground', position: [0.00125, -0.004, 0], normal: [0, -1, 0] },
    ],
    beginnerNotes: ['Electrolytic capacitors are polarized; the negative stripe matters.'],
    reviewWarnings: beginnerWarnings,
  }),
  kicad('Button_Switch_THT.3dshapes/SW_PUSH_6mm.step', {
    id: 'kicad-tactile-button-6mm',
    label: '6mm tactile push button',
    componentId: 'model-button-6mm-kicad',
    componentName: '6mm Tactile Button model',
    description: 'Common four-leg breadboard tactile button shape.',
    family: 'input',
    keywords: ['button', 'push button', 'tactile', 'switch', '6mm'],
    exactness: 'generic',
    category: 'input',
    schematicSymbol: 'button',
    defaultPins: buttonPins,
    beginnerNotes: ['Opposite legs are paired internally; rotate it correctly on a breadboard.'],
    reviewWarnings: [...beginnerWarnings, 'Four physical legs are represented as two logical switch sides.'],
  }),
  sparkfun('3dmodels/Switch.3dshapes/Slide_SPDT_PTH_11.6x4.0mm.step', {
    id: 'sparkfun-slide-switch',
    label: 'Slide switch',
    componentId: 'model-slide-switch-sparkfun',
    componentName: 'Slide Switch model',
    description: 'Three-pin slide switch for beginner input projects.',
    family: 'input',
    keywords: ['switch', 'slide switch', 'spdt', 'input'],
    exactness: 'generic',
    category: 'input',
    schematicSymbol: 'button',
    defaultPins: connectorPins(3),
    beginnerNotes: ['The center pin usually connects to one side or the other depending on slider position.'],
    reviewWarnings: beginnerWarnings,
  }),
  antmicro('sw-slide-e-switch-eg1218/SW_Slide_E-Switch_EG1218.gltf', {
    id: 'antmicro-slide-switch-eg1218',
    label: 'E-Switch EG1218 slide switch',
    componentId: 'model-slide-switch-eg1218-antmicro',
    componentName: 'E-Switch EG1218 Slide Switch model',
    description: 'Direct glTF slide switch model from Antmicro.',
    family: 'input',
    keywords: ['switch', 'slide switch', 'eg1218', 'input', 'antmicro'],
    exactness: 'exact',
    category: 'input',
    schematicSymbol: 'button',
    defaultPins: connectorPins(3),
    beginnerNotes: ['Native glTF source can be installed without STEP conversion.'],
    reviewWarnings: beginnerWarnings,
  }),
  sparkfun('3dmodels/Resistor.3dshapes/Trimpot 3386U With Knob.step', {
    id: 'sparkfun-trimpot',
    label: 'Trimpot potentiometer',
    componentId: 'model-trimpot-sparkfun',
    componentName: 'Trimpot Potentiometer model',
    description: 'Small adjustable resistor for analog input lessons.',
    family: 'input',
    keywords: ['potentiometer', 'trimpot', 'knob', 'analog', 'variable resistor'],
    exactness: 'generic',
    category: 'input',
    schematicSymbol: 'potentiometer',
    defaultPins: connectorPins(3),
    beginnerNotes: ['The middle pin is usually the wiper output.'],
    reviewWarnings: beginnerWarnings,
  }),
  sparkfun('3dmodels/Display.3dshapes/UG-2864KSWLG01.step', {
    id: 'sparkfun-oled-128x64',
    label: 'Small OLED display',
    componentId: 'model-oled-128x64-sparkfun',
    componentName: 'OLED Display model',
    description: 'Small OLED display body for SSD1306-style screen projects.',
    family: 'display',
    keywords: ['oled', 'ssd1306', 'display', 'screen', 'i2c'],
    exactness: 'generic',
    category: 'display',
    schematicSymbol: 'display',
    defaultPins: i2cModulePins,
    beginnerNotes: ['Many OLED modules use VCC, GND, SCL, and SDA pins.'],
    reviewWarnings: [...beginnerWarnings, 'Module board pin order varies by vendor.'],
  }),
  sparkfun('3dmodels/Electromechanical.3dshapes/Buzzer_9mm_SMD.step', {
    id: 'sparkfun-buzzer-9mm',
    label: '9mm buzzer',
    componentId: 'model-buzzer-9mm-sparkfun',
    componentName: '9mm Buzzer model',
    description: 'Small buzzer package for sound output projects.',
    family: 'actuator',
    keywords: ['buzzer', 'beeper', 'sound', 'speaker', 'piezo'],
    exactness: 'generic',
    category: 'actuator',
    schematicSymbol: 'speaker',
    defaultPins: twoLeadPins(0.0076),
    beginnerNotes: ['Check whether your buzzer is active or passive before coding it.'],
    reviewWarnings: beginnerWarnings,
  }),
  antmicro('buzzer-smd-cmi-9705-0380-smt-tr/Buzzer_SMD_CMI-9705-0380-SMT-TR.gltf', {
    id: 'antmicro-smd-buzzer-cmi',
    label: 'SMD buzzer CMI-9705',
    componentId: 'model-smd-buzzer-cmi-antmicro',
    componentName: 'CMI-9705 SMD Buzzer model',
    description: 'Direct glTF buzzer model from Antmicro.',
    family: 'actuator',
    keywords: ['buzzer', 'beeper', 'sound', 'piezo', 'antmicro'],
    exactness: 'exact',
    category: 'actuator',
    schematicSymbol: 'speaker',
    defaultPins: twoLeadPins(0.006),
    beginnerNotes: ['Native glTF source can be installed without STEP conversion.'],
    reviewWarnings: beginnerWarnings,
  }),
  sparkfun('3dmodels/Sensor.3dshapes/SHT40.step', {
    id: 'sparkfun-sht40-sensor',
    label: 'SHT40 temperature/humidity sensor',
    componentId: 'model-sht40-sensor-sparkfun',
    componentName: 'SHT40 Sensor model',
    description: 'Small I2C environment sensor package.',
    family: 'sensor',
    keywords: ['sht40', 'temperature', 'humidity', 'sensor', 'i2c'],
    exactness: 'package',
    category: 'sensor',
    schematicSymbol: 'sensor',
    defaultPins: i2cModulePins,
    beginnerNotes: ['Often appears on breakout boards; the bare chip model is not the full module.'],
    reviewWarnings: [...beginnerWarnings, 'This is package-level geometry, not a full breakout board.'],
  }),
  sparkfun('3dmodels/Sensor.3dshapes/ST_VL53L1x.step', {
    id: 'sparkfun-vl53l1x-sensor',
    label: 'VL53L1X distance sensor package',
    componentId: 'model-vl53l1x-sensor-sparkfun',
    componentName: 'VL53L1X Sensor model',
    description: 'Time-of-flight distance sensor package.',
    family: 'sensor',
    keywords: ['vl53l1x', 'distance', 'tof', 'sensor', 'i2c'],
    exactness: 'package',
    category: 'sensor',
    schematicSymbol: 'sensor',
    defaultPins: i2cModulePins,
    beginnerNotes: ['Package-only model; beginner modules include a carrier board.'],
    reviewWarnings: [...beginnerWarnings, 'This is package-level geometry, not a full breakout board.'],
  }),
  kicad('Relay_THT.3dshapes/Relay_DPDT_Finder_40.52.step', {
    id: 'kicad-relay-dpdt',
    label: 'Through-hole relay',
    componentId: 'model-relay-tht-kicad',
    componentName: 'Through-hole Relay model',
    description: 'Relay body for explaining high-current switching modules.',
    family: 'actuator',
    keywords: ['relay', 'switch', 'high current', 'actuator'],
    exactness: 'generic',
    category: 'actuator',
    schematicSymbol: 'relay',
    defaultPins: connectorPins(8),
    beginnerNotes: ['Do not connect motors or mains loads directly to ESP32 GPIO.'],
    reviewWarnings: [...beginnerWarnings, 'Relay pinouts vary; use a module or datasheet before wiring.'],
  }),
  sparkfun('3dmodels/Connector.3dshapes/JST_PTH-2.step', {
    id: 'sparkfun-jst-ph-2',
    label: 'JST 2-pin connector',
    componentId: 'model-jst-2pin-sparkfun',
    componentName: 'JST 2-pin Connector model',
    description: 'Common two-pin battery/connector body.',
    family: 'connector',
    keywords: ['jst', 'connector', 'battery', '2 pin'],
    exactness: 'generic',
    category: 'misc',
    schematicSymbol: 'generic-rect',
    defaultPins: connectorPins(2),
    beginnerNotes: ['Useful for recognizing battery and sensor connectors.'],
    reviewWarnings: beginnerWarnings,
  }),
  antmicro('conn-jst-sh-1x4-sm04b-srss-tb-lf-sn/Conn_JST_SH_1x4_SM04B-SRSS-TB-LF-SN.gltf', {
    id: 'antmicro-jst-sh-4',
    label: 'JST SH 4-pin connector',
    componentId: 'model-jst-sh-4-antmicro',
    componentName: 'JST SH 4-pin Connector model',
    description: 'Exact JST SH 1x4 connector glTF model.',
    family: 'connector',
    keywords: ['jst', 'connector', '4 pin', 'stemma', 'qwiic', 'i2c'],
    exactness: 'exact',
    category: 'misc',
    schematicSymbol: 'generic-rect',
    defaultPins: connectorPins(4, 0.001),
    beginnerNotes: ['Qwiic/STEMMA QT style wiring often uses four pins: GND, VCC, SDA, SCL.'],
    reviewWarnings: beginnerWarnings,
  }),
  kicad('Connector_PinHeader_2.54mm.3dshapes/PinHeader_1x04_P2.54mm_Vertical.step', {
    id: 'kicad-pin-header-1x4',
    label: '1x4 pin header',
    componentId: 'model-pin-header-1x4-kicad',
    componentName: '1x4 Pin Header model',
    description: 'Straight 2.54mm pin header used on many modules.',
    family: 'connector',
    keywords: ['pin header', 'header', 'dupont', '4 pin', '2.54mm'],
    exactness: 'generic',
    category: 'misc',
    schematicSymbol: 'generic-rect',
    defaultPins: connectorPins(4),
    beginnerNotes: ['The physical header only tells you spacing, not signal meaning.'],
    reviewWarnings: beginnerWarnings,
  }),
  sparkfun('3dmodels/Connector.3dshapes/Screw_Terminal_3.5mm_2P_Blue.step', {
    id: 'sparkfun-screw-terminal-2p',
    label: '2-pin screw terminal',
    componentId: 'model-screw-terminal-2p-sparkfun',
    componentName: '2-pin Screw Terminal model',
    description: 'Blue screw terminal for power and motor connections.',
    family: 'connector',
    keywords: ['screw terminal', 'terminal block', 'connector', 'power', 'motor'],
    exactness: 'generic',
    category: 'power',
    schematicSymbol: 'generic-rect',
    defaultPins: connectorPins(2, 0.0035),
    beginnerNotes: ['Good visual cue for external power; verify voltage before connecting.'],
    reviewWarnings: beginnerWarnings,
  }),
  antmicro('usb-c-receptacle-gct-usb4105-gf-a/USB-C_Receptacle_GCT_USB4105-GF-A.gltf', {
    id: 'antmicro-usb-c-gct',
    label: 'USB-C receptacle',
    componentId: 'model-usb-c-receptacle-antmicro',
    componentName: 'USB-C Receptacle model',
    description: 'Exact USB-C connector glTF model.',
    family: 'connector',
    keywords: ['usb', 'usb-c', 'connector', 'power', 'serial'],
    exactness: 'exact',
    category: 'power',
    schematicSymbol: 'generic-rect',
    defaultPins: connectorPins(24, 0.0005),
    beginnerNotes: ['Useful for recognizing the USB-C port on newer ESP32 boards.'],
    reviewWarnings: [...beginnerWarnings, 'USB-C electrical pinout is complex; do not wire from visual geometry alone.'],
  }),
  antmicro('usb-micro-b-receptacle-molex-473460001/USB-Micro-B_Receptacle_Molex_473460001.gltf', {
    id: 'antmicro-usb-micro-b',
    label: 'Micro USB-B receptacle',
    componentId: 'model-usb-micro-b-antmicro',
    componentName: 'Micro USB-B Receptacle model',
    description: 'Exact Micro USB-B connector glTF model.',
    family: 'connector',
    keywords: ['usb', 'micro usb', 'connector', 'power', 'serial'],
    exactness: 'exact',
    category: 'power',
    schematicSymbol: 'generic-rect',
    defaultPins: connectorPins(5, 0.00065),
    beginnerNotes: ['Useful for recognizing the USB port on many ESP32 boards.'],
    reviewWarnings: [...beginnerWarnings, 'USB electrical pinout is complex; do not wire from visual geometry alone.'],
  }),
  antmicro('barreljack-pin2mm-pj-002ah/BarrelJack_Pin2mm_PJ-002AH.gltf', {
    id: 'antmicro-barrel-jack',
    label: 'DC barrel jack',
    componentId: 'model-barrel-jack-antmicro',
    componentName: 'DC Barrel Jack model',
    description: 'Direct glTF barrel jack model for external power examples.',
    family: 'power',
    keywords: ['barrel jack', 'dc jack', 'power connector', 'vin'],
    exactness: 'exact',
    category: 'power',
    schematicSymbol: 'generic-rect',
    defaultPins: connectorPins(3),
    beginnerNotes: ['External power needs careful voltage checks before connecting to ESP32 boards.'],
    reviewWarnings: beginnerWarnings,
  }),
  kicad('Battery.3dshapes/BatteryHolder_Keystone_2462_2xAA.step', {
    id: 'kicad-aa-battery-holder',
    label: '2xAA battery holder',
    componentId: 'model-aa-battery-holder-kicad',
    componentName: '2xAA Battery Holder model',
    description: 'Battery holder shape for portable power lessons.',
    family: 'power',
    keywords: ['battery', 'aa', 'holder', 'power'],
    exactness: 'generic',
    category: 'power',
    schematicSymbol: 'generic-rect',
    defaultPins: [
      { id: 'positive', label: '+', type: 'power_out', position: [-0.004, -0.004, 0], normal: [0, -1, 0] },
      { id: 'negative', label: '-', type: 'ground', position: [0.004, -0.004, 0], normal: [0, -1, 0] },
    ],
    beginnerNotes: ['Two AA batteries are about 3V when fresh alkaline cells are used.'],
    reviewWarnings: beginnerWarnings,
  }),
  kicad('Diode_THT.3dshapes/D_DO-35_SOD27_P7.62mm_Horizontal.step', {
    id: 'kicad-signal-diode',
    label: 'Small signal diode',
    componentId: 'model-signal-diode-kicad',
    componentName: 'Small Signal Diode model',
    description: 'Glass diode body for polarity and protection lessons.',
    family: 'protection',
    keywords: ['diode', '1n4148', 'protection', 'polarity'],
    exactness: 'generic',
    category: 'misc',
    schematicSymbol: 'generic-rect',
    defaultPins: [
      { id: 'anode', label: 'A', type: 'digital_io', position: [-0.00381, -0.004, 0], normal: [0, -1, 0] },
      { id: 'cathode', label: 'K', type: 'digital_io', position: [0.00381, -0.004, 0], normal: [0, -1, 0] },
    ],
    beginnerNotes: ['The stripe marks the cathode side on many diodes.'],
    reviewWarnings: beginnerWarnings,
  }),
]

export const LOCAL_IMPORT_ONLY_ASSETS: ModelAssetCandidate[] = [
  {
    id: 'snapmagic-exact-part-placeholder',
    label: 'Exact component from SnapMagic',
    componentId: 'local-snapmagic-exact-part',
    componentName: 'SnapMagic exact part model',
    description: 'Use when you know a manufacturer part number and download the STEP locally.',
    family: 'exact component',
    keywords: ['snapmagic', 'snapeda', 'exact part', 'manufacturer part number', 'step'],
    sourceId: 'snapmagic',
    sourceUrl: 'https://www.snapeda.com/',
    licenseName: 'Free download; redistribution must be reviewed per asset',
    licenseUrl: 'https://www.snapeda.com/',
    licenseUse: 'local-import-only',
    attribution: 'SnapMagic Search and original part vendors',
    format: 'step',
    exactness: 'exact',
    category: 'misc',
    schematicSymbol: 'generic-rect',
    modelFileName: 'snapmagic-local.step',
    defaultPins: [],
    beginnerNotes: ['Download locally, then import through Catalog Editor after checking terms.'],
    reviewWarnings: ['Local import only. Do not bundle unless redistribution rights are clear.'],
  },
  {
    id: 'ultralibrarian-exact-part-placeholder',
    label: 'Exact component from Ultra Librarian',
    componentId: 'local-ultralibrarian-exact-part',
    componentName: 'Ultra Librarian exact part model',
    description: 'Use when a distributor/manufacturer links to Ultra Librarian CAD files.',
    family: 'exact component',
    keywords: ['ultra librarian', 'exact part', 'manufacturer part number', 'step'],
    sourceId: 'ultra-librarian',
    sourceUrl: 'https://www.ultralibrarian.com/',
    licenseName: 'Free download; redistribution must be reviewed per asset',
    licenseUrl: 'https://www.ultralibrarian.com/legal/',
    licenseUse: 'local-import-only',
    attribution: 'Ultra Librarian and original part vendors',
    format: 'step',
    exactness: 'exact',
    category: 'misc',
    schematicSymbol: 'generic-rect',
    modelFileName: 'ultralibrarian-local.step',
    defaultPins: [],
    beginnerNotes: ['Download locally, then import through Catalog Editor after checking terms.'],
    reviewWarnings: ['Local import only. Do not bundle unless redistribution rights are clear.'],
  },
]

export const BLOCKED_MODEL_ASSETS: ModelAssetCandidate[] = [
  {
    id: 'blocked-paid-model-marketplace',
    label: 'Paid marketplace electronics model',
    componentId: 'blocked-paid-model-marketplace',
    componentName: 'Paid model placeholder',
    description: 'Policy fixture for paid or subscription-only assets.',
    family: 'policy',
    keywords: ['paid', 'premium', 'subscription', 'marketplace'],
    sourceId: 'paid-marketplace',
    sourceUrl: 'https://example.com/paid-models',
    licenseName: 'Paid or unclear license',
    licenseUrl: 'https://example.com/paid-models/license',
    licenseUse: 'blocked',
    attribution: 'Not importable',
    format: 'glb',
    exactness: 'generic',
    category: 'misc',
    schematicSymbol: 'generic-rect',
    modelFileName: 'blocked.glb',
    defaultPins: [],
    beginnerNotes: ['Do not use paid or unclear-license assets for this library.'],
    reviewWarnings: ['Blocked by the no-paid-models rule.'],
  },
]

export const MODEL_LIBRARY_ASSETS: ModelAssetCandidate[] = [
  ...STARTER_MODEL_ASSETS,
  ...LOCAL_IMPORT_ONLY_ASSETS,
  ...BLOCKED_MODEL_ASSETS,
]
