import type { Project } from '../project/schema'
import type { LearningRecipe } from '../learning/types'

export type Difficulty = 'beginner' | 'intermediate' | 'advanced'

export interface TemplateEntry {
  id: string
  title: string
  description: string
  difficulty: Difficulty
  tags: string[]
  recipe: LearningRecipe
  project: Project
}

const BLINK_LED_RECIPE: LearningRecipe = {
  id: 'blink-led',
  goal: 'Learn how a GPIO pin can turn an LED on and off through a safe current-limiting resistor.',
  estimatedTime: '10-15 min',
  concepts: ['GPIO output', 'series resistor', 'ground path', 'timer behavior'],
  requiredParts: [
    { componentId: 'led-5mm-red', quantity: 1, why: 'The LED is the visible output you will blink.' },
    { componentId: 'resistor-220r', quantity: 1, why: 'The resistor limits current so the LED and ESP32 pin stay safe.' },
  ],
  wiringSteps: [
    {
      id: 'gpio-to-resistor',
      from: 'board.gpio16',
      to: 'r1.in',
      title: 'Send GPIO16 into the resistor',
      why: 'The GPIO pin is the controllable output, but the resistor must be first in line to limit current.',
      expected: 'GPIO16 connects to the input side of the resistor.',
    },
    {
      id: 'resistor-to-led',
      from: 'r1.out',
      to: 'led1.anode',
      title: 'Feed the protected signal into the LED anode',
      why: 'The LED anode is the positive side; it receives the GPIO signal after current has been limited.',
      expected: 'The resistor output connects to the LED anode.',
    },
    {
      id: 'led-to-ground',
      from: 'led1.cathode',
      to: 'board.gnd_l',
      title: 'Complete the path back to ground',
      why: 'Current only flows when it has a complete loop from GPIO through the LED and back to GND.',
      expected: 'The LED cathode connects to board ground.',
    },
  ],
  checkpoints: [
    { id: 'drc-clean', kind: 'drc', title: 'Circuit is electrically safe', expected: 'DRC shows no errors before simulation.' },
    { id: 'sim-blinks', kind: 'simulation', title: 'LED blinks in simulation', expected: 'After pressing Play, the LED changes state every second.', behaviorId: 'blink', afterMs: 1000 },
    { id: 'code-timer', kind: 'code', title: 'Firmware has a timer behavior', expected: 'Generated code contains the blink behavior and GPIO setup.', behaviorId: 'blink' },
  ],
  hardwareNotes: [
    'Use the resistor in series with the LED, not parallel.',
    'The shorter LED leg is usually cathode and should go to ground.',
  ],
  followUpExperiments: [
    'Change the timer from 1000 ms to 250 ms and observe the blink speed.',
    'Move the LED to another safe GPIO and rebuild.',
  ],
  steps: [
    {
      id: 'overview',
      kind: 'overview',
      title: 'What you are building',
      body: 'A GPIO pin will repeatedly turn an LED on and off.',
      why: 'This is the smallest useful ESP32 output circuit and teaches the safe GPIO-to-part pattern.',
      action: 'Review the parts, then move to the first wire.',
    },
    {
      id: 'wire-gpio-to-resistor',
      kind: 'wire',
      title: 'Wire GPIO16 to the resistor',
      body: 'Start at board.gpio16 and connect it to r1.in.',
      why: 'The resistor protects the LED and GPIO by limiting current.',
      action: 'Click board.gpio16, then click r1.in.',
      refs: ['board.gpio16', 'r1.in'],
      wiringStepId: 'gpio-to-resistor',
    },
    {
      id: 'wire-resistor-to-led',
      kind: 'wire',
      title: 'Wire the resistor to the LED',
      body: 'Connect r1.out to led1.anode.',
      why: 'The LED receives the controlled signal after current is limited.',
      action: 'Click r1.out, then click led1.anode.',
      refs: ['r1.out', 'led1.anode'],
      wiringStepId: 'resistor-to-led',
    },
    {
      id: 'wire-led-to-ground',
      kind: 'wire',
      title: 'Wire the LED back to ground',
      body: 'Connect led1.cathode to board.gnd_l.',
      why: 'Ground completes the circuit loop.',
      action: 'Click led1.cathode, then click board.gnd_l.',
      refs: ['led1.cathode', 'board.gnd_l'],
      wiringStepId: 'led-to-ground',
    },
    {
      id: 'simulate',
      kind: 'simulate',
      title: 'Run the behavior simulation',
      body: 'The timer behavior toggles led1.anode every 1000 ms.',
      why: 'Simulation proves the logic before you touch real hardware.',
      action: 'Open Sim and press Play.',
      checkpointId: 'sim-blinks',
    },
    {
      id: 'code',
      kind: 'code',
      title: 'Connect the behavior to generated firmware',
      body: 'The generated ESP-IDF code configures the GPIO and toggles it from a timer task.',
      why: 'This connects the visual behavior to code that can run on the ESP32.',
      action: 'Open Code and look for the blink behavior.',
      checkpointId: 'code-timer',
    },
  ],
}

export const TEMPLATES: TemplateEntry[] = [
  {
    id: 'blink-led',
    title: 'Blink LED',
    description: 'Toggle an LED on and off every second using a periodic timer.',
    difficulty: 'beginner',
    tags: ['LED', 'GPIO', 'Timer'],
    recipe: BLINK_LED_RECIPE,
    project: {
      schemaVersion: 1,
      name: 'Blink LED',
      target: 'esp32',
      board: 'esp32-devkitc-v4',
      components: [
        {
          instance: 'r1',
          componentId: 'resistor-220r',
          position: [0.02, 0, 0.01],
          rotation: [0, 0, 0],
          pinAssignments: { in: 'GPIO16' },
        },
        {
          instance: 'led1',
          componentId: 'led-5mm-red',
          position: [0.04, 0, 0.01],
          rotation: [0, 0, 0],
          pinAssignments: { anode: 'GPIO16' },
        },
      ],
      nets: [
        { id: 'n1', endpoints: ['board.gpio16', 'r1.in'] },
        { id: 'n2', endpoints: ['r1.out', 'led1.anode'] },
        { id: 'n3', endpoints: ['led1.cathode', 'board.gnd_l'] },
      ],
      behaviors: [
        {
          id: 'blink',
          trigger: { type: 'timer', period_ms: 1000 },
          actions: [{ type: 'toggle', target: 'led1.anode' }],
        },
      ],
      app: { wifi: { enabled: false }, log_level: 'info' },
    },
  },
  {
    id: 'button-led',
    title: 'Button + LED',
    description: 'Press a button to turn an LED on; release to turn it off.',
    difficulty: 'beginner',
    tags: ['LED', 'Button', 'GPIO edge'],
    recipe: {
      id: 'button-led',
      goal: 'Learn how an ESP32 reads a button input and uses it to control an LED output.',
      estimatedTime: '15-20 min',
      concepts: ['GPIO input', 'internal pull-up', 'falling edge', 'debounce', 'GPIO output'],
      requiredParts: [
        { componentId: 'button-6mm', quantity: 1, why: 'The button gives the ESP32 a physical input to read.' },
        { componentId: 'led-5mm-red', quantity: 1, why: 'The LED shows the output response.' },
        { componentId: 'resistor-220r', quantity: 1, why: 'The resistor protects the LED and GPIO output.' },
      ],
      wiringSteps: [
        {
          id: 'button-to-gpio',
          from: 'board.gpio4',
          to: 'btn1.a',
          title: 'Connect the button input to GPIO4',
          why: 'GPIO4 watches the button so firmware can react when it is pressed.',
          expected: 'GPIO4 connects to one side of the button.',
        },
        {
          id: 'button-to-ground',
          from: 'btn1.b',
          to: 'board.gnd_r',
          title: 'Connect the other side of the button to ground',
          why: 'With an internal pull-up, pressing the button pulls the input low and creates a clear falling edge.',
          expected: 'The button closes a path from GPIO4 to GND.',
        },
        {
          id: 'gpio-to-resistor',
          from: 'board.gpio16',
          to: 'r1.in',
          title: 'Send GPIO16 into the resistor',
          why: 'GPIO16 is the LED output, and the resistor keeps current safe.',
          expected: 'GPIO16 connects to the resistor input.',
        },
        {
          id: 'resistor-to-led',
          from: 'r1.out',
          to: 'led1.anode',
          title: 'Connect the resistor to the LED anode',
          why: 'The LED turns on when the protected GPIO signal drives the anode.',
          expected: 'The resistor output connects to the LED anode.',
        },
        {
          id: 'led-to-ground',
          from: 'led1.cathode',
          to: 'board.gnd_l',
          title: 'Complete the LED ground path',
          why: 'The LED needs a path back to ground to light.',
          expected: 'The LED cathode connects to ground.',
        },
      ],
      checkpoints: [
        { id: 'drc-clean', kind: 'drc', title: 'Button and LED wiring are safe', expected: 'DRC shows no errors before simulation.' },
        { id: 'sim-press', kind: 'simulation', title: 'Button controls the LED', expected: 'Pressing the button in 3D turns the LED on, and releasing turns it off.', behaviorId: 'on_press', requiresInput: 'Click and hold the button in the 3D viewer.' },
        { id: 'code-edge', kind: 'code', title: 'Firmware reacts to GPIO edges', expected: 'Generated code contains button press and release behavior.', behaviorId: 'on_press' },
      ],
      hardwareNotes: [
        'The button uses an internal pull-up, so no external pull-up resistor is needed for this first project.',
        'A falling edge means the input changes from high to low when the button is pressed.',
      ],
      followUpExperiments: [
        'Change the behavior so each press toggles the LED instead of holding it on.',
        'Add a second LED and make the button switch between them.',
      ],
      steps: [
        {
          id: 'overview',
          kind: 'overview',
          title: 'What you are building',
          body: 'A button input will control an LED output.',
          why: 'This teaches the basic input -> firmware -> output loop used in many electronics projects.',
          action: 'Review the button and LED parts, then wire the input side.',
        },
        {
          id: 'wire-button-gpio',
          kind: 'wire',
          title: 'Wire GPIO4 to the button',
          body: 'Connect board.gpio4 to btn1.a.',
          why: 'GPIO4 is the input the ESP32 watches for button changes.',
          action: 'Click board.gpio4, then click btn1.a.',
          refs: ['board.gpio4', 'btn1.a'],
          wiringStepId: 'button-to-gpio',
        },
        {
          id: 'wire-button-ground',
          kind: 'wire',
          title: 'Wire the button to ground',
          body: 'Connect btn1.b to board.gnd_r.',
          why: 'Pressing the button pulls the watched input to ground.',
          action: 'Click btn1.b, then click board.gnd_r.',
          refs: ['btn1.b', 'board.gnd_r'],
          wiringStepId: 'button-to-ground',
        },
        {
          id: 'wire-led-output',
          kind: 'wire',
          title: 'Wire GPIO16 through the LED resistor',
          body: 'Connect board.gpio16 to r1.in.',
          why: 'The LED output still needs current limiting.',
          action: 'Click board.gpio16, then click r1.in.',
          refs: ['board.gpio16', 'r1.in'],
          wiringStepId: 'gpio-to-resistor',
        },
        {
          id: 'wire-resistor-led',
          kind: 'wire',
          title: 'Wire the resistor to the LED',
          body: 'Connect r1.out to led1.anode.',
          why: 'This feeds the safe output signal into the LED.',
          action: 'Click r1.out, then click led1.anode.',
          refs: ['r1.out', 'led1.anode'],
          wiringStepId: 'resistor-to-led',
        },
        {
          id: 'wire-led-ground',
          kind: 'wire',
          title: 'Wire the LED to ground',
          body: 'Connect led1.cathode to board.gnd_l.',
          why: 'The output circuit needs a return path.',
          action: 'Click led1.cathode, then click board.gnd_l.',
          refs: ['led1.cathode', 'board.gnd_l'],
          wiringStepId: 'led-to-ground',
        },
        {
          id: 'simulate',
          kind: 'simulate',
          title: 'Test the input in simulation',
          body: 'Press the button model in the 3D viewer while simulation is running.',
          why: 'This proves the firmware reacts to an input before you flash hardware.',
          action: 'Open Sim, press Play, then click and hold the button.',
          checkpointId: 'sim-press',
        },
      ],
    },
    project: {
      schemaVersion: 1,
      name: 'Button + LED',
      target: 'esp32',
      board: 'esp32-devkitc-v4',
      components: [
        {
          instance: 'btn1',
          componentId: 'button-6mm',
          position: [0.02, 0, 0.02],
          rotation: [0, 0, 0],
          pinAssignments: { a: 'GPIO4' },
          internalPullups: { a: true },
        },
        {
          instance: 'r1',
          componentId: 'resistor-220r',
          position: [0.02, 0, 0.01],
          rotation: [0, 0, 0],
          pinAssignments: { in: 'GPIO16' },
        },
        {
          instance: 'led1',
          componentId: 'led-5mm-red',
          position: [0.04, 0, 0.01],
          rotation: [0, 0, 0],
          pinAssignments: { anode: 'GPIO16' },
        },
      ],
      nets: [
        { id: 'n1', endpoints: ['board.gpio4', 'btn1.a'] },
        { id: 'n2', endpoints: ['btn1.b', 'board.gnd_r'] },
        { id: 'n3', endpoints: ['board.gpio16', 'r1.in'] },
        { id: 'n4', endpoints: ['r1.out', 'led1.anode'] },
        { id: 'n5', endpoints: ['led1.cathode', 'board.gnd_l'] },
      ],
      behaviors: [
        {
          id: 'on_press',
          trigger: { type: 'gpio_edge', source: 'btn1.a', edge: 'falling' },
          debounce_ms: 50,
          actions: [{ type: 'set_output', target: 'led1.anode', value: 'on' }],
        },
        {
          id: 'on_release',
          trigger: { type: 'gpio_edge', source: 'btn1.a', edge: 'rising' },
          debounce_ms: 50,
          actions: [{ type: 'set_output', target: 'led1.anode', value: 'off' }],
        },
      ],
      app: { wifi: { enabled: false }, log_level: 'info' },
    },
  },
  {
    id: 'sos-blinker',
    title: 'SOS Blinker',
    description: 'Flash the classic SOS Morse code pattern on a LED at boot.',
    difficulty: 'beginner',
    tags: ['LED', 'Sequence', 'Morse'],
    recipe: {
      id: 'sos-blinker',
      goal: 'Learn how a sequence of timed actions can create a recognizable LED pattern.',
      estimatedTime: '15-20 min',
      concepts: ['boot behavior', 'action sequence', 'delay', 'Morse code', 'LED safety'],
      requiredParts: [
        { componentId: 'led-5mm-red', quantity: 1, why: 'The LED shows the Morse code pattern.' },
        { componentId: 'resistor-220r', quantity: 1, why: 'The resistor protects the LED during repeated flashes.' },
      ],
      wiringSteps: [
        {
          id: 'gpio-to-resistor',
          from: 'board.gpio16',
          to: 'r1.in',
          title: 'Send GPIO16 into the resistor',
          why: 'GPIO16 drives the LED pattern, and the resistor limits current.',
          expected: 'GPIO16 connects to the resistor input.',
        },
        {
          id: 'resistor-to-led',
          from: 'r1.out',
          to: 'led1.anode',
          title: 'Feed the LED through the resistor',
          why: 'The LED should receive the signal after current is limited.',
          expected: 'The resistor output connects to the LED anode.',
        },
        {
          id: 'led-to-ground',
          from: 'led1.cathode',
          to: 'board.gnd_l',
          title: 'Complete the LED circuit',
          why: 'Ground completes the loop so the LED can turn on.',
          expected: 'The LED cathode connects to ground.',
        },
      ],
      checkpoints: [
        { id: 'drc-clean', kind: 'drc', title: 'SOS circuit is safe', expected: 'DRC shows no errors before simulation.' },
        { id: 'sim-sos', kind: 'simulation', title: 'LED plays the SOS pattern', expected: 'After Play starts, the LED flashes short-short-short, long-long-long, short-short-short.', behaviorId: 'sos', afterMs: 2000 },
        { id: 'code-sequence', kind: 'code', title: 'Firmware contains a boot sequence', expected: 'Generated code contains the boot-triggered sequence and delays.', behaviorId: 'sos' },
      ],
      hardwareNotes: [
        'Boot behavior runs once after the ESP32 starts.',
        'Long and short delays create the Morse rhythm.',
      ],
      followUpExperiments: [
        'Change the delays to make the pattern faster or slower.',
        'Replace SOS with your initials in Morse code.',
      ],
      steps: [
        {
          id: 'overview',
          kind: 'overview',
          title: 'What you are building',
          body: 'An LED will flash an SOS pattern once when the ESP32 boots.',
          why: 'This teaches how firmware can run a planned sequence of timed actions.',
          action: 'Review the pattern, then wire the LED safely.',
        },
        {
          id: 'wire-gpio-resistor',
          kind: 'wire',
          title: 'Wire GPIO16 to the resistor',
          body: 'Connect board.gpio16 to r1.in.',
          why: 'This is the driven output for the flashing pattern.',
          action: 'Click board.gpio16, then click r1.in.',
          refs: ['board.gpio16', 'r1.in'],
          wiringStepId: 'gpio-to-resistor',
        },
        {
          id: 'wire-resistor-led',
          kind: 'wire',
          title: 'Wire the resistor to the LED',
          body: 'Connect r1.out to led1.anode.',
          why: 'The LED gets a safe current-limited signal.',
          action: 'Click r1.out, then click led1.anode.',
          refs: ['r1.out', 'led1.anode'],
          wiringStepId: 'resistor-to-led',
        },
        {
          id: 'wire-led-ground',
          kind: 'wire',
          title: 'Wire the LED to ground',
          body: 'Connect led1.cathode to board.gnd_l.',
          why: 'The LED needs ground to complete the circuit.',
          action: 'Click led1.cathode, then click board.gnd_l.',
          refs: ['led1.cathode', 'board.gnd_l'],
          wiringStepId: 'led-to-ground',
        },
        {
          id: 'simulate',
          kind: 'simulate',
          title: 'Watch the sequence run',
          body: 'The behavior runs at boot and uses delays to create short and long flashes.',
          why: 'This shows how timing creates meaning from a simple output.',
          action: 'Open Sim and press Play.',
          checkpointId: 'sim-sos',
        },
        {
          id: 'experiment',
          kind: 'experiment',
          title: 'Make the pattern yours',
          body: 'Try changing one delay or adding another sequence.',
          why: 'Small changes make it easier to understand how code becomes behavior.',
          action: 'Edit the behavior or ask Codex to help change the pattern.',
        },
      ],
    },
    project: {
      schemaVersion: 1,
      name: 'SOS Blinker',
      target: 'esp32',
      board: 'esp32-devkitc-v4',
      components: [
        {
          instance: 'r1',
          componentId: 'resistor-220r',
          position: [0.02, 0, 0.01],
          rotation: [0, 0, 0],
          pinAssignments: { in: 'GPIO16' },
        },
        {
          instance: 'led1',
          componentId: 'led-5mm-red',
          position: [0.04, 0, 0.01],
          rotation: [0, 0, 0],
          pinAssignments: { anode: 'GPIO16' },
        },
      ],
      nets: [
        { id: 'n1', endpoints: ['board.gpio16', 'r1.in'] },
        { id: 'n2', endpoints: ['r1.out', 'led1.anode'] },
        { id: 'n3', endpoints: ['led1.cathode', 'board.gnd_l'] },
      ],
      behaviors: [
        {
          id: 'sos',
          trigger: { type: 'boot' },
          actions: [
            {
              type: 'sequence',
              actions: [
                // S: · · ·
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 400 },
                // O: — — —
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 600 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 600 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 600 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 400 },
                // S: · · ·
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'on' },
                { type: 'delay', ms: 200 },
                { type: 'set_output', target: 'led1.anode', value: 'off' },
              ],
            },
          ],
        },
      ],
      app: { wifi: { enabled: false }, log_level: 'info' },
    },
  },
]

export const DIFFICULTY_COLOR: Record<Difficulty, string> = {
  beginner:     '#34c759',
  intermediate: '#ff9500',
  advanced:     '#ff3b30',
}
