import { app, BrowserWindow, dialog, ipcMain } from 'electron'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { readFile, writeFile, mkdir, readdir } from 'fs/promises'
import { existsSync } from 'fs'
import { homedir } from 'os'
import { spawn, type ChildProcessWithoutNullStreams } from 'child_process'
import { randomUUID } from 'crypto'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const ESP_AI_HOME = join(homedir(), '.esp-ai')
const PROJECTS_ROOT = join(homedir(), 'esp-ai', 'projects')
const IDF_PATH = process.env.ESP_AI_IDF_PATH ?? '/Users/marco/esp/esp-idf'

const runs = new Map<string, ChildProcessWithoutNullStreams>()

let mainWindow: BrowserWindow | null = null

function createWindow() {
  const win = new BrowserWindow({
    width: 1400,
    height: 900,
    title: 'esp-ai',
    webPreferences: {
      preload: join(__dirname, '../preload/preload.mjs'),
      sandbox: false
    }
  })
  mainWindow = win
  win.on('closed', () => { mainWindow = null })

  if (process.env.ELECTRON_RENDERER_URL) {
    win.loadURL(process.env.ELECTRON_RENDERER_URL)
    win.webContents.openDevTools({ mode: 'detach' })
  } else {
    win.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

ipcMain.handle('pickGlb', async () => {
  const r = await dialog.showOpenDialog({
    title: 'Select a .glb model',
    filters: [{ name: '3D Model', extensions: ['glb', 'gltf'] }],
    properties: ['openFile']
  })
  if (r.canceled || !r.filePaths[0]) return null
  const data = await readFile(r.filePaths[0])
  return { path: r.filePaths[0], data: new Uint8Array(data) }
})

ipcMain.handle('pickComponent', async () => {
  const r = await dialog.showOpenDialog({
    title: 'Open component.json',
    filters: [{ name: 'Component JSON', extensions: ['json'] }],
    properties: ['openFile']
  })
  if (r.canceled || !r.filePaths[0]) return null
  const jsonPath = r.filePaths[0]
  const json = await readFile(jsonPath, 'utf8')
  let glbData: Uint8Array | null = null
  let glbName: string | null = null
  try {
    const parsed = JSON.parse(json)
    if (parsed.model) {
      const candidate = join(dirname(jsonPath), parsed.model)
      if (existsSync(candidate)) {
        glbData = new Uint8Array(await readFile(candidate))
        glbName = parsed.model
      }
    }
    if (!glbData) {
      // fallback: any .glb in same dir
      const sibs = await readdir(dirname(jsonPath))
      const glb = sibs.find((f) => f.toLowerCase().endsWith('.glb'))
      if (glb) {
        glbData = new Uint8Array(await readFile(join(dirname(jsonPath), glb)))
        glbName = glb
      }
    }
  } catch { /* ignore — return json only */ }
  return { jsonPath, json, glbData, glbName }
})

ipcMain.handle('listCatalog', async () => {
  const root = join(ESP_AI_HOME, 'catalog')
  if (!existsSync(root)) return []
  const dirs = await readdir(root, { withFileTypes: true })
  const out: Array<{ id: string; json: any; glbData: Uint8Array | null }> = []
  for (const d of dirs) {
    if (!d.isDirectory()) continue
    const jsonPath = join(root, d.name, 'component.json')
    if (!existsSync(jsonPath)) continue
    try {
      const json = JSON.parse(await readFile(jsonPath, 'utf8'))
      let glbData: Uint8Array | null = null
      if (json.model && existsSync(join(root, d.name, json.model))) {
        glbData = new Uint8Array(await readFile(join(root, d.name, json.model)))
      }
      out.push({ id: json.id ?? d.name, json, glbData })
    } catch { /* skip bad entry */ }
  }
  return out
})

ipcMain.handle('writeBundle', async (_e, id: string, glbName: string, glbData: Uint8Array, jsonText: string) => {
  if (!id) throw new Error('id is required')
  const dir = join(ESP_AI_HOME, 'catalog', id)
  await mkdir(dir, { recursive: true })
  await writeFile(join(dir, glbName), Buffer.from(glbData))
  await writeFile(join(dir, 'component.json'), jsonText, 'utf8')
  return dir
})

// ---- M5: flash pipeline ----

function projectDirFor(name: string): string {
  const safe = name.replace(/[^a-zA-Z0-9_-]/g, '_') || 'untitled'
  return join(PROJECTS_ROOT, safe)
}

ipcMain.handle('projectWrite', async (_e, name: string, target: string, files: Record<string, string>) => {
  const dir = projectDirFor(name)
  await mkdir(join(dir, 'main'), { recursive: true })
  for (const [rel, content] of Object.entries(files)) {
    const abs = join(dir, rel)
    await mkdir(dirname(abs), { recursive: true })
    await writeFile(abs, content, 'utf8')
  }
  // Top-level CMakeLists.txt — ESP-IDF expects this.
  const topCMake = [
    '# AUTO-GENERATED BY esp-ai. DO NOT EDIT.',
    'cmake_minimum_required(VERSION 3.16)',
    'include($ENV{IDF_PATH}/tools/cmake/project.cmake)',
    `project(${name.replace(/[^a-zA-Z0-9_-]/g, '_') || 'esp_ai_project'})`,
    ''
  ].join('\n')
  await writeFile(join(dir, 'CMakeLists.txt'), topCMake, 'utf8')
  return { dir, target }
})

ipcMain.handle('listSerialPorts', async () => {
  try {
    const entries = await readdir('/dev')
    return entries
      .filter((f) => /^cu\.(usb|SLAB|wch|tty\.usb)/i.test(f))
      .map((f) => `/dev/${f}`)
      .sort()
  } catch {
    return []
  }
})

ipcMain.handle('idfStart', async (_e, opts: {
  name: string; target: string; op: 'build' | 'flash' | 'monitor' | 'clean'; port?: string
}) => {
  const dir = projectDirFor(opts.name)
  if (!existsSync(dir)) throw new Error(`Project dir does not exist: ${dir} (write first)`)
  if (!existsSync(IDF_PATH)) throw new Error(`ESP-IDF not found at ${IDF_PATH} (set ESP_AI_IDF_PATH)`)

  const needsTarget = !existsSync(join(dir, 'build'))
  const portArg = opts.port ? ` -p ${JSON.stringify(opts.port)}` : ''
  let cmd: string
  switch (opts.op) {
    case 'build':
      cmd = needsTarget
        ? `idf.py set-target ${opts.target} && idf.py build`
        : `idf.py build`
      break
    case 'flash':
      if (!opts.port) throw new Error('Flash requires a serial port')
      cmd = `idf.py${portArg} flash`
      break
    case 'monitor':
      if (!opts.port) throw new Error('Monitor requires a serial port')
      cmd = `idf.py${portArg} monitor`
      break
    case 'clean':
      cmd = `idf.py fullclean`
      break
  }

  const runId = randomUUID()
  const shell = `source ${JSON.stringify(join(IDF_PATH, 'export.sh'))} 1>/dev/null && cd ${JSON.stringify(dir)} && ${cmd}`
  // GUI apps on macOS don't inherit the terminal PATH, so Homebrew's python3 is
  // not visible to bash -l. Prepend the common Homebrew prefixes explicitly so
  // export.sh can activate the venv and put idf.py on PATH.
  const extraPaths = ['/opt/homebrew/bin', '/opt/homebrew/sbin', '/usr/local/bin', '/usr/local/sbin']
  const PATH = [...extraPaths, process.env.PATH ?? ''].join(':')
  const child = spawn('bash', ['-c', shell], {
    env: { ...process.env, PATH, IDF_PATH, PYTHONUNBUFFERED: '1' }
  }) as ChildProcessWithoutNullStreams
  runs.set(runId, child)

  const emit = (stream: 'stdout' | 'stderr', data: Buffer) => {
    const text = data.toString('utf8')
    mainWindow?.webContents.send('idf:log', { runId, stream, text })
  }
  child.stdout.on('data', (d) => emit('stdout', d))
  child.stderr.on('data', (d) => emit('stderr', d))
  child.on('exit', (code, signal) => {
    runs.delete(runId)
    mainWindow?.webContents.send('idf:exit', { runId, code, signal })
  })
  child.on('error', (err) => {
    mainWindow?.webContents.send('idf:log', { runId, stream: 'stderr', text: `spawn error: ${err.message}\n` })
  })
  return { runId, cwd: dir, cmd }
})

// ---- Project save / open ----

ipcMain.handle('saveProject', async (_e, project: unknown, suggestedName: string, existingPath?: string) => {
  let filePath = existingPath
  if (!filePath) {
    const safe = (suggestedName || 'untitled').replace(/[^a-zA-Z0-9_-]/g, '_')
    const r = await dialog.showSaveDialog({
      title: 'Save project',
      defaultPath: join(homedir(), 'esp-ai', `${safe}.espai.json`),
      filters: [{ name: 'esp-ai project', extensions: ['espai.json'] }]
    })
    if (r.canceled || !r.filePath) return null
    filePath = r.filePath
  }
  await mkdir(dirname(filePath), { recursive: true })
  await writeFile(filePath, JSON.stringify(project, null, 2), 'utf8')
  return filePath
})

ipcMain.handle('openProject', async () => {
  const r = await dialog.showOpenDialog({
    title: 'Open project',
    filters: [{ name: 'esp-ai project', extensions: ['espai.json', 'json'] }],
    properties: ['openFile']
  })
  if (r.canceled || !r.filePaths[0]) return null
  const text = await readFile(r.filePaths[0], 'utf8')
  const parsed = JSON.parse(text)
  if (parsed.schemaVersion !== 1) throw new Error('Unsupported project schema version')
  return { project: parsed, path: r.filePaths[0] }
})

ipcMain.handle('idfStop', async (_e, runId: string) => {
  const child = runs.get(runId)
  if (!child) return { ok: false, reason: 'not running' }
  child.kill('SIGINT')
  // fallback hard kill
  setTimeout(() => { if (runs.has(runId)) child.kill('SIGKILL') }, 1500)
  return { ok: true }
})

app.on('before-quit', () => {
  for (const child of runs.values()) child.kill('SIGKILL')
})

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow()
})
