import type { PartKnowledgeRecord } from './types'

export type CuratedPart = PartKnowledgeRecord & { synonyms: string[] }

export const CURATED_PARTS: CuratedPart[] = [
  {
    id: 'led-5mm-red',
    label: '5mm LED',
    family: 'indicator',
    synonyms: ['led', 'red led', 'light emitting diode', 'indicator light'],
    confidence: 'high',
    source: 'local-catalog',
    catalogMatchId: 'led-5mm-red',
    explanation: 'A simple output part that lights up when current flows in the correct direction.',
    safetyNotes: ['Use a series resistor such as 220 ohm before connecting an LED to an ESP32 GPIO.'],
    importantPins: [
      { id: 'anode', label: 'Anode', type: 'digital_in', why: 'Positive side of the LED.' },
      { id: 'cathode', label: 'Cathode', type: 'ground', why: 'Negative side that returns to ground.' },
    ],
    requiredCompanions: [
      { componentId: 'resistor-220r', quantity: 1, reason: 'Limits LED current and protects the GPIO.' },
    ],
    sourceLinks: [],
    renderStrategy: 'catalog-glb',
    reviewRequired: false,
  },
  {
    id: 'resistor-220r',
    label: '220 ohm resistor',
    family: 'resistor',
    synonyms: ['resistor', '220r', '220 ohm', 'current limiting resistor'],
    confidence: 'high',
    source: 'local-catalog',
    catalogMatchId: 'resistor-220r',
    explanation: 'A resistor limits current and is commonly used in series with an LED.',
    safetyNotes: ['Check color bands or measure with a multimeter before relying on the value.'],
    importantPins: [
      { id: 'in', label: 'In', type: 'digital_in', why: 'Either side of a resistor can be used as input.' },
      { id: 'out', label: 'Out', type: 'digital_out', why: 'Either side of a resistor can be used as output.' },
    ],
    requiredCompanions: [],
    sourceLinks: [],
    renderStrategy: 'catalog-glb',
    reviewRequired: false,
  },
  {
    id: 'button-6mm',
    label: '6mm push button',
    family: 'input',
    synonyms: ['button', 'push button', 'tactile switch', 'switch', 'btn'],
    confidence: 'high',
    source: 'local-catalog',
    catalogMatchId: 'button-6mm',
    explanation: 'A simple input that connects two pins while pressed.',
    safetyNotes: ['Use a pull-up or pull-down strategy so the input does not float.'],
    importantPins: [
      { id: 'a', label: 'A', type: 'digital_io', why: 'One side of the switch.' },
      { id: 'b', label: 'B', type: 'digital_io', why: 'Other side of the switch.' },
    ],
    requiredCompanions: [],
    sourceLinks: [],
    renderStrategy: 'catalog-glb',
    reviewRequired: false,
  },
  {
    id: 'capacitive-soil-moisture-sensor',
    label: 'Capacitive soil moisture sensor',
    family: 'analog sensor',
    synonyms: ['soil sensor', 'moisture sensor', 'plant sensor', 'water sensor'],
    confidence: 'medium',
    source: 'curated-db',
    explanation: 'A module that outputs an analog voltage related to soil moisture.',
    safetyNotes: ['Use a 3.3V-compatible module for ESP32 ADC safety.'],
    importantPins: [
      { id: 'vcc', label: 'VCC', type: 'power_in', why: 'Powers the sensor.' },
      { id: 'gnd', label: 'GND', type: 'ground', why: 'Shared ground reference.' },
      { id: 'aout', label: 'AOUT', type: 'analog_out', why: 'Analog moisture signal.' },
    ],
    requiredCompanions: [
      { componentId: 'capacitor-100nf', quantity: 1, reason: 'Helps smooth noisy analog readings.' },
    ],
    sourceLinks: [],
    renderStrategy: 'primitive',
    reviewRequired: true,
  },
  {
    id: 'ssd1306-oled-i2c',
    label: 'SSD1306 OLED I2C display',
    family: 'display',
    synonyms: ['oled', 'display', 'screen', 'ssd1306', 'i2c display'],
    confidence: 'medium',
    source: 'curated-db',
    explanation: 'A small screen that usually communicates over I2C using SDA and SCL.',
    safetyNotes: ['Use a 3.3V logic-safe module or level shifting.'],
    importantPins: [
      { id: 'vcc', label: 'VCC', type: 'power_in', why: 'Powers the display.' },
      { id: 'gnd', label: 'GND', type: 'ground', why: 'Shared ground reference.' },
      { id: 'sda', label: 'SDA', type: 'i2c_sda', why: 'I2C data line.' },
      { id: 'scl', label: 'SCL', type: 'i2c_scl', why: 'I2C clock line.' },
    ],
    requiredCompanions: [
      { componentId: 'resistor-4k7', quantity: 2, reason: 'I2C lines may need pull-up resistors unless the module includes them.' },
    ],
    sourceLinks: [],
    renderStrategy: 'primitive',
    reviewRequired: true,
  },
  {
    id: 'pir-motion-sensor',
    label: 'PIR motion sensor',
    family: 'digital sensor',
    synonyms: ['pir', 'motion sensor', 'presence sensor', 'movement sensor'],
    confidence: 'medium',
    source: 'curated-db',
    explanation: 'A module that changes a digital output when motion is detected.',
    safetyNotes: ['Confirm output voltage before connecting to ESP32 GPIO.'],
    importantPins: [
      { id: 'vcc', label: 'VCC', type: 'power_in', why: 'Powers the sensor.' },
      { id: 'out', label: 'OUT', type: 'digital_out', why: 'Motion signal.' },
      { id: 'gnd', label: 'GND', type: 'ground', why: 'Shared ground reference.' },
    ],
    requiredCompanions: [],
    sourceLinks: [],
    renderStrategy: 'primitive',
    reviewRequired: true,
  },
  {
    id: 'sg90-servo',
    label: 'SG90 micro servo',
    family: 'motor',
    synonyms: ['servo', 'sg90', 'micro servo', 'motor'],
    confidence: 'medium',
    source: 'curated-db',
    explanation: 'A small motor module that moves to commanded angles using a PWM control signal.',
    safetyNotes: ['Power servos from a separate supply when possible; do not draw motor current from an ESP32 GPIO.'],
    importantPins: [
      { id: 'vcc', label: 'VCC', type: 'power_in', why: 'Motor power.' },
      { id: 'gnd', label: 'GND', type: 'ground', why: 'Shared ground reference.' },
      { id: 'sig', label: 'SIG', type: 'pwm', why: 'PWM control signal.' },
    ],
    requiredCompanions: [
      { componentId: 'external-5v-supply', quantity: 1, reason: 'Servos often need more current than the board regulator can safely supply.' },
    ],
    sourceLinks: [],
    renderStrategy: 'generic-block',
    reviewRequired: true,
  },
]
