export const themeColorNames = [
  'background',
  'surface',
  'recessed',
  'card',
  'text',
  'textStrong',
  'textMetaAccent',
  'textMuted',
  'textSoft',
  'border',
  'borderStrong',
  'focus',
  'buttonPrimaryBg',
  'buttonPrimaryText',
  'buttonPrimaryBorder',
  'buttonSecondaryText',
  'buttonSecondaryBorder',
  'errorText',
  'errorBorder',
  'errorBg',
  'successBorder',
  'successText',
  'successBg',
  'blockedBorder',
  'blockedSubtleText',
  'blockedBg',
  'blockedSubtleBg',
  'blockedText',
  'metricValue',
  'emptyText',
] as const

export type ThemeColorName = typeof themeColorNames[number]
export type ThemeColors = Record<ThemeColorName, string>

export const darkTheme = {
  background: '#0c0d0f',
  surface: '#111317',
  recessed: '#0b0c0e',
  card: '#0c0e11',
  // Against background #0c0d0f these text tokens meet WCAG AA normal text:
  // text 13.60:1, textStrong 17.27:1, textMetaAccent 7.86:1,
  // textMuted 5.05:1, textSoft 8.97:1.
  text: '#d5d8dc',
  textStrong: '#eef2f5',
  textMetaAccent: '#8fa7c4',
  textMuted: '#79838e',
  textSoft: '#a9b1bb',
  border: '#25282d',
  borderStrong: '#30343a',
  focus: '#6bb6ff',
  buttonPrimaryBg: '#183657',
  buttonPrimaryText: '#dcecff',
  buttonPrimaryBorder: '#356895',
  buttonSecondaryText: '#b8c6d5',
  buttonSecondaryBorder: '#3b4652',
  errorText: '#ffb4a8',
  errorBorder: '#9b4b4b',
  errorBg: '#1b1010',
  successBorder: '#315a42',
  successText: '#8ed5a8',
  successBg: '#0f1a14',
  blockedBorder: '#3a3030',
  blockedSubtleText: '#8d7373',
  blockedBg: '#211313',
  blockedSubtleBg: '#151010',
  blockedText: '#e9a7a7',
  metricValue: '#e7eef7',
  emptyText: '#6d747d',
} as const satisfies ThemeColors

export const MONOSPACE_FONT_STACK = "'SF Mono', Menlo, Consolas, 'Liberation Mono', 'DejaVu Sans Mono', monospace"
