// Template assembly — produces main.c, CMakeLists.txt, sdkconfig.defaults from the IR.
// Deterministic output (stable ordering, no timestamps) so regeneration is idempotent.

import type { Project, Behavior, Action } from '../project/schema'
import { buildIr, type Ir } from './ir'
import { catalog } from '../catalog'

export interface GeneratedFiles {
  'main/app_main.c': string
  'main/CMakeLists.txt': string
  'sdkconfig.defaults': string
}

const HEADER = `// AUTO-GENERATED BY Circuitiny. DO NOT EDIT.
// Regenerate via the Code pane; manual edits will be overwritten.
`

export function generate(project: Project): { files: GeneratedFiles; ir: Ir } {
  const ir = buildIr(project)
  const sorted = [...ir.components].sort((a, b) => a.instance.localeCompare(b.instance))

  const includes = new Set<string>(['<stdio.h>', '"freertos/FreeRTOS.h"', '"freertos/task.h"', '"esp_log.h"', '"nvs_flash.h"'])
  for (const c of sorted) c.driverIncludes.forEach((i) => includes.add(quoted(i)))
  if (sorted.some((c) => c.pins.some((p) => /digital|analog_out|pwm/.test(p.type)))) includes.add('"driver/gpio.h"')
  if (ir.buses.some((b) => b.kind === 'i2c')) includes.add('"driver/i2c.h"')
  if (ir.app.wifi) { includes.add('"esp_wifi.h"'); includes.add('"esp_event.h"') }
  if (ir.app.mqtt) includes.add('"mqtt_client.h"')
  if (ir.app.httpClient) includes.add('"esp_http_client.h"')

  const includeBlock = [...includes].sort().map((i) => `#include ${i}`).join('\n')

  const pinDefines = sorted.flatMap((c) =>
    c.pins.filter((p) => p.boardGpioNum !== null)
      .map((p) => `#define PIN_${upperSnake(c.instance)}_${upperSnake(p.id)} ${p.boardGpioNum}`)
  )

  // Resolve behavior targets and emit per-behavior tasks / boot hooks.
  const pinResolver = buildPinResolver(project)

  // ── gpio_edge behaviors ──────────────────────────────────────────────────
  // Group by resolved source pin so press+release on the same GPIO share one task.
  const edgeGroups: EdgeGroup[] = []
  const edgePinExprs = new Set<string>()
  for (const beh of project.behaviors) {
    if (beh.trigger.type !== 'gpio_edge') continue
    const pinExpr = pinResolver(beh.trigger.source)
    if (!pinExpr) continue
    edgePinExprs.add(pinExpr)
    let g = edgeGroups.find((eg) => eg.pinExpr === pinExpr)
    if (!g) { g = { pinExpr, behaviors: [] }; edgeGroups.push(g) }
    g.behaviors.push({ beh, edge: beh.trigger.edge ?? 'rising' })
  }
  const edgeTasks = edgeGroups.map((g) => emitGpioEdgeTask(g, pinResolver))
  const edgeInitLines = edgeGroups.flatMap((g) => [
    `// --- edge input: ${g.pinExpr} ---`,
    `gpio_reset_pin(${g.pinExpr});`,
    `gpio_set_direction(${g.pinExpr}, GPIO_MODE_INPUT);`,
    `gpio_set_pull_mode(${g.pinExpr}, GPIO_PULLUP_ONLY);`,
  ])
  const edgeLaunchers = edgeGroups.map((g, i) =>
    `xTaskCreate(gpio_poll_${sanitize(g.pinExpr)}_task, "gp_${i}", 3072, NULL, 5, NULL);`
  )

  // gpio.h is already pulled in by digital pins, but guarantee it when edge triggers are present.
  if (edgeGroups.length > 0) includes.add('"driver/gpio.h"')

  const initLines = sorted.flatMap((c) => emitInit(c, edgePinExprs))

  const i2cInit = ir.buses.filter((b) => b.kind === 'i2c').map(emitI2cInit)

  const bootActions: string[] = []
  const behaviorTasks: string[] = []
  const behaviorLaunchers: string[] = []
  for (const beh of project.behaviors) {
    if (beh.trigger.type === 'boot') {
      bootActions.push(`// behavior ${beh.id}`)
      bootActions.push(...emitActions(beh.actions, pinResolver))
    } else if (beh.trigger.type === 'timer') {
      behaviorTasks.push(emitTimerTask(beh, pinResolver))
      behaviorLaunchers.push(`xTaskCreate(beh_${sanitize(beh.id)}_task, "${sanitize(beh.id)}", 3072, NULL, 5, NULL);`)
    }
    // gpio_edge → handled above; other triggers (wifi_connected, mqtt_received) not yet implemented
  }

  const mainC = [
    HEADER,
    includeBlock,
    '',
    `static const char *TAG = "circuitiny";`,
    '',
    ...(pinDefines.length ? [pinDefines.join('\n'), ''] : []),
    ...i2cInit,
    ...behaviorTasks,
    ...edgeTasks,
    `void app_main(void)`,
    `{`,
    `    ESP_ERROR_CHECK(nvs_flash_init());`,
    `    ESP_LOGI(TAG, "boot: ${ir.board} / ${sorted.length} component(s) / ${ir.buses.length} bus(es)");`,
    ...initLines.map((l) => `    ${l}`),
    ...edgeInitLines.map((l) => `    ${l}`),
    ...(ir.app.wifi ? ['    // TODO: wifi_init_sta() — credentials from NVS'] : []),
    ...(ir.app.mqtt ? ['    // TODO: mqtt_app_start()'] : []),
    ...bootActions.map((l) => `    ${l}`),
    ...behaviorLaunchers.map((l) => `    ${l}`),
    ...edgeLaunchers.map((l) => `    ${l}`),
    `}`,
    ''
  ].filter((s) => s !== null).join('\n')

  const cmakeHeader = `# AUTO-GENERATED BY Circuitiny. DO NOT EDIT.\n# Regenerate via the Code pane; manual edits will be overwritten.\n`
  const cmake = [
    cmakeHeader,
    `idf_component_register(`,
    `    SRCS "app_main.c"`,
    `    INCLUDE_DIRS "."`,
    `    REQUIRES ${['driver', 'nvs_flash', 'esp_event', 'log',
       ...(ir.app.wifi ? ['esp_wifi'] : []),
       ...(ir.app.mqtt ? ['mqtt'] : []),
       ...(ir.app.httpClient || ir.app.httpServer ? ['esp_http_client', 'esp_http_server'] : []),
       ...Array.from(new Set(sorted.flatMap((c) => c.cmakeRequires)))
     ].sort().map((r) => `"${r}"`).join(' ')}`,
    `)`,
    ''
  ].join('\n')

  const sdkconfigHeader = `# AUTO-GENERATED BY Circuitiny. DO NOT EDIT.\n# Regenerate via the Code pane; manual edits will be overwritten.\n`
  const boardDef = catalog.getBoard(project.board)
  const boardFlags = boardSdkconfigFlags(ir.target, boardDef?.usbPins ?? [])
  const sdkconfig = [
    sdkconfigHeader,
    `CONFIG_IDF_TARGET="${ir.target}"`,
    `CONFIG_LOG_DEFAULT_LEVEL_${ir.app.logLevel.toUpperCase()}=y`,
    ...(ir.app.wifi ? ['CONFIG_ESP_WIFI_ENABLED=y'] : []),
    ...(ir.app.mqtt ? ['CONFIG_MQTT_PROTOCOL_311=y'] : []),
    ...boardFlags,
    ''
  ].join('\n')

  return {
    ir,
    files: {
      'main/app_main.c': mainC,
      'main/CMakeLists.txt': cmake,
      'sdkconfig.defaults': sdkconfig
    }
  }
}

function emitInit(
  c: { instance: string; pins: Array<{ id: string; type: string; boardGpioNum: number | null }> },
  skipMacros: Set<string> = new Set()
): string[] {
  const lines: string[] = []
  for (const p of c.pins) {
    if (p.boardGpioNum === null) continue
    const pinMacro = `PIN_${upperSnake(c.instance)}_${upperSnake(p.id)}`
    if (skipMacros.has(pinMacro)) continue   // gpio_edge source — configured by edge init section
    // 'digital_in'  = component input  → MCU drives it   → GPIO_MODE_OUTPUT
    // 'digital_out' = component output → MCU reads it    → GPIO_MODE_INPUT
    // 'digital_io'  = bidirectional    → default OUTPUT
    if (p.type === 'digital_in' || p.type === 'digital_io') {
      lines.push(`gpio_reset_pin(${pinMacro});`)
      lines.push(`gpio_set_direction(${pinMacro}, GPIO_MODE_OUTPUT);`)
    } else if (p.type === 'digital_out') {
      lines.push(`gpio_reset_pin(${pinMacro});`)
      lines.push(`gpio_set_direction(${pinMacro}, GPIO_MODE_INPUT);`)
    }
  }
  if (lines.length) lines.unshift(`// --- ${c.instance} (${c.pins.length} pins) ---`)
  return lines
}

type EdgeGroup = {
  pinExpr: string
  behaviors: Array<{ beh: Behavior; edge: 'rising' | 'falling' | 'both' }>
}

function emitGpioEdgeTask(group: EdgeGroup, resolve: PinResolver): string {
  const name = sanitize(group.pinExpr)
  const dispatchLines: string[] = []
  for (const { beh, edge } of group.behaviors) {
    const actionLines = emitActions(beh.actions, resolve).map((l) => `                ${l}`)
    if (edge === 'both') {
      dispatchLines.push(`            // behavior ${beh.id} — any edge`)
      dispatchLines.push(...actionLines)
    } else {
      const cond = edge === 'rising' ? 'cur_ == 1' : 'cur_ == 0'
      dispatchLines.push(`            if (${cond}) { // behavior ${beh.id}`)
      dispatchLines.push(...actionLines)
      dispatchLines.push(`            }`)
    }
  }
  return [
    `static void gpio_poll_${name}_task(void *arg)`,
    `{`,
    `    int last_ = gpio_get_level(${group.pinExpr});`,
    `    for (;;) {`,
    `        vTaskDelay(pdMS_TO_TICKS(10));`,
    `        int cur_ = gpio_get_level(${group.pinExpr});`,
    `        if (cur_ != last_) {`,
    `            last_ = cur_;`,
    ...(dispatchLines.length ? dispatchLines : ['            // no actions']),
    `        }`,
    `    }`,
    `}`,
    ``
  ].join('\n')
}

function emitI2cInit(b: { id: string; pins: Record<string, string | null> }): string {
  const sdaNum = b.pins.sda?.replace('GPIO', '')
  const sclNum = b.pins.scl?.replace('GPIO', '')
  return [
    `static void init_${b.id}(void)`,
    `{`,
    `    i2c_config_t cfg = {`,
    `        .mode = I2C_MODE_MASTER,`,
    `        .sda_io_num = ${sdaNum}, .scl_io_num = ${sclNum},`,
    `        .sda_pullup_en = GPIO_PULLUP_ENABLE, .scl_pullup_en = GPIO_PULLUP_ENABLE,`,
    `        .master.clk_speed = 400000,`,
    `    };`,
    `    i2c_param_config(I2C_NUM_0, &cfg);`,
    `    i2c_driver_install(I2C_NUM_0, cfg.mode, 0, 0, 0);`,
    `}`,
    ''
  ].join('\n')
}

function upperSnake(s: string) { return s.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase() }
function quoted(s: string) { return s.startsWith('"') || s.startsWith('<') ? s : `"${s}"` }
function sanitize(s: string) { return s.replace(/[^a-zA-Z0-9_]/g, '_') }

// Resolve "instance.pin" (or "board.pinId") to a C expression usable in gpio_* calls.
// For board pins: returns the raw GPIO number string (e.g. "16").
// For component pins directly wired to a board GPIO: returns the PIN_* macro.
// For component pins reachable only through passive components: traces through nets
// and returns the raw GPIO number of the first board pin found.
type PinResolver = (target: string) => string | null

function buildPinResolver(project: Project): PinResolver {
  const board = catalog.getBoard(project.board)

  // Walk nets, crossing through 2-pin passives, to find the board GPIO label.
  function traceToGpioLabel(ref: string, visited = new Set<string>()): string | null {
    if (visited.has(ref)) return null
    visited.add(ref)
    if (ref.startsWith('board.')) {
      if (!board) return null
      const p = board.pins.find((x) => x.id === ref.split('.')[1])
      return (p && /^\d+$/.test(p.label)) ? p.label : null
    }
    const net = project.nets.find((n) => n.endpoints.includes(ref))
    if (!net) return null
    for (const ep of net.endpoints) {
      if (ep === ref) continue
      if (ep.startsWith('board.')) {
        const label = traceToGpioLabel(ep, visited)
        if (label) return label
      } else {
        const [inst] = ep.split('.')
        const comp = project.components.find((c) => c.instance === inst)
        if (!comp) continue
        const def = catalog.getComponent(comp.componentId)
        if (!def || def.pins.length !== 2) continue   // passives only
        for (const p of def.pins) {
          const other = `${inst}.${p.id}`
          if (other === ep) continue
          const label = traceToGpioLabel(other, visited)
          if (label) return label
        }
      }
    }
    return null
  }

  return (target) => {
    if (!target.includes('.')) return null
    const [owner, pinId] = target.split('.')
    if (owner === 'board') {
      if (!board) return null
      const p = board.pins.find((x) => x.id === pinId)
      return (p && /^\d+$/.test(p.label)) ? p.label : null
    }
    if (!project.components.find((c) => c.instance === owner)) return null

    // Check if this pin has a direct board GPIO via a net (no passives needed).
    const directNet = project.nets.find((n) => n.endpoints.includes(`${owner}.${pinId}`))
    const directBoard = directNet?.endpoints.find((e) => e.startsWith('board.'))
    if (directBoard) {
      // Direct connection → return named PIN macro (matches the #define).
      return `PIN_${upperSnake(owner)}_${upperSnake(pinId)}`
    }

    // Indirect (through passives) → trace to board GPIO number.
    return traceToGpioLabel(`${owner}.${pinId}`)
  }
}

function emitActions(actions: Action[], resolve: PinResolver): string[] {
  const out: string[] = []
  for (const a of actions) {
    switch (a.type) {
      case 'set_output': {
        const pin = resolve(a.target)
        if (!pin) { out.push(`// skip set_output: unresolved ${a.target}`); break }
        out.push(`gpio_set_level(${pin}, ${a.value === 'on' ? 1 : 0});`)
        break
      }
      case 'toggle': {
        const pin = resolve(a.target)
        if (!pin) { out.push(`// skip toggle: unresolved ${a.target}`); break }
        const stateVar = `s_${sanitize(a.target)}`
        out.push(`static int ${stateVar} = 0; ${stateVar} ^= 1; gpio_set_level(${pin}, ${stateVar});`)
        break
      }
      case 'log': {
        const macro = a.level === 'warn' ? 'ESP_LOGW' : a.level === 'error' ? 'ESP_LOGE' : 'ESP_LOGI'
        out.push(`${macro}(TAG, "${escapeC(a.message)}");`)
        break
      }
      case 'delay':
        out.push(`vTaskDelay(pdMS_TO_TICKS(${a.ms | 0}));`)
        break
      case 'sequence':
        out.push(...emitActions(a.actions, resolve))
        break
      default:
        out.push(`// unsupported action: ${a.type}`)
    }
  }
  return out
}

function emitTimerTask(beh: Behavior, resolve: PinResolver): string {
  if (beh.trigger.type !== 'timer') return ''
  const period = Math.max(1, beh.trigger.period_ms | 0)
  const name = sanitize(beh.id)
  const body = emitActions(beh.actions, resolve).map((l) => `        ${l}`).join('\n')
  return [
    `static void beh_${name}_task(void *arg)`,
    `{`,
    `    TickType_t last = xTaskGetTickCount();`,
    `    for (;;) {`,
    `        vTaskDelayUntil(&last, pdMS_TO_TICKS(${period}));`,
    body || '        // no actions',
    `    }`,
    `}`,
    ''
  ].join('\n')
}

function escapeC(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
}

function boardSdkconfigFlags(target: string, usbPins: string[]): string[] {
  const hasUsb = usbPins.length > 0
  // Accurate 1ms tick resolution on all chips — default Hz=100 makes pdMS_TO_TICKS(1) = 10ms.
  const flags: string[] = ['CONFIG_FREERTOS_HZ=1000']
  switch (target) {
    case 'esp32':
      flags.push('CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y')
      break
    case 'esp32s2':
      flags.push('CONFIG_ESP32S2_DEFAULT_CPU_FREQ_240=y')
      if (hasUsb) flags.push('CONFIG_ESP_CONSOLE_USB_CDC=y')
      break
    case 'esp32s3':
      flags.push('CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240=y')
      if (hasUsb) flags.push('CONFIG_ESP_CONSOLE_USB_CDC=y')
      break
    case 'esp32c3':
      flags.push('CONFIG_ESP32C3_DEFAULT_CPU_FREQ_160=y')
      if (hasUsb) flags.push('CONFIG_ESP_CONSOLE_USB_CDC=y')
      break
    case 'esp32c6':
      flags.push('CONFIG_ESP32C6_DEFAULT_CPU_FREQ_160=y')
      if (hasUsb) flags.push('CONFIG_ESP_CONSOLE_USB_CDC=y')
      // IEEE 802.15.4 (Thread/Zigbee) only when explicitly needed — saves ~100KB flash
      break
    case 'esp32h2':
      flags.push('CONFIG_ESP32H2_DEFAULT_CPU_FREQ_96=y')
      if (hasUsb) flags.push('CONFIG_ESP_CONSOLE_USB_CDC=y')
      break
  }
  return flags
}
