// Template assembly — produces main.c, CMakeLists.txt, sdkconfig.defaults from the IR.
// Deterministic output (stable ordering, no timestamps) so regeneration is idempotent.

import type { Project } from '../project/schema'
import { buildIr, type Ir } from './ir'

export interface GeneratedFiles {
  'main/app_main.c': string
  'main/CMakeLists.txt': string
  'sdkconfig.defaults': string
}

const HEADER = `// AUTO-GENERATED BY esp-ai. DO NOT EDIT.
// Regenerate via the Code pane; manual edits will be overwritten.
`

export function generate(project: Project): { files: GeneratedFiles; ir: Ir } {
  const ir = buildIr(project)
  const sorted = [...ir.components].sort((a, b) => a.instance.localeCompare(b.instance))

  const includes = new Set<string>(['<stdio.h>', '"freertos/FreeRTOS.h"', '"freertos/task.h"', '"esp_log.h"', '"nvs_flash.h"'])
  for (const c of sorted) c.driverIncludes.forEach((i) => includes.add(quoted(i)))
  if (sorted.some((c) => c.pins.some((p) => /digital|analog_out|pwm/.test(p.type)))) includes.add('"driver/gpio.h"')
  if (ir.buses.some((b) => b.kind === 'i2c')) includes.add('"driver/i2c.h"')
  if (ir.app.wifi) { includes.add('"esp_wifi.h"'); includes.add('"esp_event.h"') }
  if (ir.app.mqtt) includes.add('"mqtt_client.h"')
  if (ir.app.httpClient) includes.add('"esp_http_client.h"')

  const includeBlock = [...includes].sort().map((i) => `#include ${i}`).join('\n')

  const pinDefines = sorted.flatMap((c) =>
    c.pins.filter((p) => p.boardGpioNum !== null)
      .map((p) => `#define PIN_${upperSnake(c.instance)}_${upperSnake(p.id)} ${p.boardGpioNum}`)
  )

  const initLines = sorted.flatMap((c) => emitInit(c))

  const i2cInit = ir.buses.filter((b) => b.kind === 'i2c').map(emitI2cInit)

  const mainC = [
    HEADER,
    includeBlock,
    '',
    `static const char *TAG = "esp-ai";`,
    '',
    ...(pinDefines.length ? [pinDefines.join('\n'), ''] : []),
    ...i2cInit,
    `void app_main(void)`,
    `{`,
    `    ESP_ERROR_CHECK(nvs_flash_init());`,
    `    ESP_LOGI(TAG, "boot: ${ir.board} / ${sorted.length} component(s) / ${ir.buses.length} bus(es)");`,
    ...initLines.map((l) => `    ${l}`),
    ...(ir.app.wifi ? ['    // TODO: wifi_init_sta() — credentials from NVS'] : []),
    ...(ir.app.mqtt ? ['    // TODO: mqtt_app_start()'] : []),
    `    // Behaviors will be emitted here in M7.`,
    `}`,
    ''
  ].filter((s) => s !== null).join('\n')

  const cmake = [
    HEADER,
    `idf_component_register(`,
    `    SRCS "app_main.c"`,
    `    INCLUDE_DIRS "."`,
    `    REQUIRES ${['driver', 'nvs_flash', 'esp_event', 'log',
       ...(ir.app.wifi ? ['esp_wifi'] : []),
       ...(ir.app.mqtt ? ['mqtt'] : []),
       ...(ir.app.httpClient || ir.app.httpServer ? ['esp_http_client', 'esp_http_server'] : []),
       ...Array.from(new Set(sorted.flatMap((c) => c.cmakeRequires)))
     ].sort().map((r) => `"${r}"`).join(' ')}`,
    `)`,
    ''
  ].join('\n')

  const sdkconfig = [
    HEADER,
    `CONFIG_IDF_TARGET="${ir.target}"`,
    `CONFIG_LOG_DEFAULT_LEVEL_${ir.app.logLevel.toUpperCase()}=y`,
    ...(ir.app.wifi ? ['CONFIG_ESP_WIFI_ENABLED=y'] : []),
    ...(ir.app.mqtt ? ['CONFIG_MQTT_PROTOCOL_311=y'] : []),
    ''
  ].join('\n')

  return {
    ir,
    files: {
      'main/app_main.c': mainC,
      'main/CMakeLists.txt': cmake,
      'sdkconfig.defaults': sdkconfig
    }
  }
}

function emitInit(c: { instance: string; pins: Array<{ id: string; type: string; boardGpioNum: number | null }> }): string[] {
  const lines: string[] = []
  for (const p of c.pins) {
    if (p.boardGpioNum === null) continue
    const pinMacro = `PIN_${upperSnake(c.instance)}_${upperSnake(p.id)}`
    if (p.type === 'digital_out' || p.type === 'digital_io') {
      lines.push(`gpio_reset_pin(${pinMacro});`)
      lines.push(`gpio_set_direction(${pinMacro}, GPIO_MODE_OUTPUT);`)
    } else if (p.type === 'digital_in') {
      lines.push(`gpio_reset_pin(${pinMacro});`)
      lines.push(`gpio_set_direction(${pinMacro}, GPIO_MODE_INPUT);`)
    }
  }
  if (lines.length) lines.unshift(`// --- ${c.instance} (${c.pins.length} pins) ---`)
  return lines
}

function emitI2cInit(b: { id: string; pins: Record<string, string | null> }): string {
  const sdaNum = b.pins.sda?.replace('GPIO', '')
  const sclNum = b.pins.scl?.replace('GPIO', '')
  return [
    `static void init_${b.id}(void)`,
    `{`,
    `    i2c_config_t cfg = {`,
    `        .mode = I2C_MODE_MASTER,`,
    `        .sda_io_num = ${sdaNum}, .scl_io_num = ${sclNum},`,
    `        .sda_pullup_en = GPIO_PULLUP_ENABLE, .scl_pullup_en = GPIO_PULLUP_ENABLE,`,
    `        .master.clk_speed = 400000,`,
    `    };`,
    `    i2c_param_config(I2C_NUM_0, &cfg);`,
    `    i2c_driver_install(I2C_NUM_0, cfg.mode, 0, 0, 0);`,
    `}`,
    ''
  ].join('\n')
}

function upperSnake(s: string) { return s.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase() }
function quoted(s: string) { return s.startsWith('"') || s.startsWith('<') ? s : `"${s}"` }
