import type { CSSProperties } from 'react'
import { darkTheme, MONOSPACE_FONT_STACK } from '../theme/colors'
import {
  BORDER_RADIUS_MEDIUM,
  BORDER_RADIUS_SMALL,
  BORDER_WIDTH_ACCENT,
  FONT_SIZE_CAPTION,
  FONT_SIZE_LABEL,
  FONT_SIZE_VALUE,
  GRID_MIN_COLUMN_WIDTH,
  PHOTO_THUMB_HEIGHT,
  PHOTO_THUMB_WIDTH,
  SECTION_MIN_HEIGHT,
  SPACING_2XS,
  SPACING_BUTTON_X,
  SPACING_CARD_Y,
  SPACING_CONTROL_Y,
  SPACING_FIELD,
  SPACING_MEDIUM,
  SPACING_SMALL,
  SPACING_XS,
  SPACING_XL,
  TEXTAREA_MIN_HEIGHT,
} from '../theme/designTokens'

export const COLORS = darkTheme

type StyleKey =
  | 'root' | 'section' | 'header' | 'meta' | 'row' | 'input' | 'textarea'
  | 'primaryButton' | 'secondaryButton' | 'photoStrip' | 'photoThumb'
  | 'findings' | 'finding' | 'findingTitle' | 'findingBody' | 'empty'
  | 'errorText' | 'muted' | 'metrics' | 'metric' | 'metricValue'
  | 'metricLabel' | 'actionGrid' | 'actionAllowed' | 'actionBlocked'

export const styles = {
  root: {
    height: '100%',
    overflow: 'auto',
    padding: SPACING_XL,
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: `repeat(auto-fit, minmax(${GRID_MIN_COLUMN_WIDTH}, 1fr))`,
    gap: SPACING_XL,
    background: COLORS.background,
    color: COLORS.text,
    fontSize: FONT_SIZE_LABEL,
  },
  section: {
    border: `1px solid ${COLORS.border}`,
    borderRadius: BORDER_RADIUS_MEDIUM,
    background: COLORS.surface,
    padding: SPACING_XL,
    minHeight: SECTION_MIN_HEIGHT,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING_MEDIUM,
    color: COLORS.textStrong,
    fontWeight: 700,
    marginBottom: SPACING_MEDIUM,
  },
  meta: {
    color: COLORS.textMetaAccent,
    fontFamily: MONOSPACE_FONT_STACK,
    fontSize: FONT_SIZE_CAPTION,
    fontWeight: 500,
  },
  row: { display: 'flex', gap: SPACING_SMALL, marginBottom: SPACING_MEDIUM },
  input: {
    flex: 1,
    minWidth: 0,
    background: COLORS.recessed,
    color: COLORS.text,
    border: `1px solid ${COLORS.borderStrong}`,
    borderRadius: BORDER_RADIUS_SMALL,
    padding: `${SPACING_CONTROL_Y} ${SPACING_FIELD}`,
    fontSize: FONT_SIZE_LABEL,
  },
  textarea: {
    width: '100%',
    minHeight: TEXTAREA_MIN_HEIGHT,
    resize: 'vertical',
    boxSizing: 'border-box',
    background: COLORS.recessed,
    color: COLORS.text,
    border: `1px solid ${COLORS.borderStrong}`,
    borderRadius: BORDER_RADIUS_SMALL,
    padding: SPACING_FIELD,
    fontSize: FONT_SIZE_LABEL,
    marginBottom: SPACING_FIELD,
  },
  primaryButton: {
    background: COLORS.buttonPrimaryBg,
    color: COLORS.buttonPrimaryText,
    border: `1px solid ${COLORS.buttonPrimaryBorder}`,
    borderRadius: BORDER_RADIUS_SMALL,
    padding: `${SPACING_CONTROL_Y} ${SPACING_BUTTON_X}`,
    fontSize: FONT_SIZE_LABEL,
    cursor: 'pointer',
  },
  secondaryButton: {
    background: 'transparent',
    color: COLORS.buttonSecondaryText,
    border: `1px solid ${COLORS.buttonSecondaryBorder}`,
    borderRadius: BORDER_RADIUS_SMALL,
    padding: `${SPACING_CONTROL_Y} ${SPACING_BUTTON_X}`,
    fontSize: FONT_SIZE_LABEL,
    cursor: 'pointer',
  },
  photoStrip: {
    display: 'grid',
    gridTemplateColumns: `${PHOTO_THUMB_WIDTH} 1fr`,
    gap: SPACING_MEDIUM,
    alignItems: 'center',
    marginBottom: SPACING_MEDIUM,
  },
  photoThumb: {
    width: PHOTO_THUMB_WIDTH,
    height: PHOTO_THUMB_HEIGHT,
    objectFit: 'cover',
    borderRadius: BORDER_RADIUS_SMALL,
    border: `1px solid ${COLORS.borderStrong}`,
  },
  findings: { display: 'flex', flexDirection: 'column', gap: SPACING_SMALL, marginTop: SPACING_MEDIUM },
  finding: {
    borderLeft: `${BORDER_WIDTH_ACCENT}px solid ${COLORS.borderStrong}`,
    background: COLORS.card,
    padding: `${SPACING_CARD_Y} ${SPACING_SMALL}`,
    borderRadius: BORDER_RADIUS_SMALL,
  },
  findingTitle: { color: COLORS.textStrong, fontWeight: 700 },
  findingBody: { color: COLORS.textSoft, marginTop: SPACING_XS, lineHeight: 1.35 },
  empty: { color: COLORS.emptyText, fontStyle: 'italic', marginTop: SPACING_MEDIUM },
  errorText: {
    color: COLORS.errorText,
    borderLeft: `${BORDER_WIDTH_ACCENT}px solid ${COLORS.errorBorder}`,
    background: COLORS.errorBg,
    padding: `${SPACING_CARD_Y} ${SPACING_SMALL}`,
    borderRadius: BORDER_RADIUS_SMALL,
    marginTop: SPACING_MEDIUM,
  },
  muted: { color: COLORS.textMuted, lineHeight: 1.35, marginTop: SPACING_MEDIUM },
  metrics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))',
    gap: SPACING_SMALL,
    marginBottom: SPACING_MEDIUM,
  },
  metric: { background: COLORS.card, border: `1px solid ${COLORS.border}`, borderRadius: BORDER_RADIUS_SMALL, padding: SPACING_CARD_Y },
  metricValue: { color: COLORS.metricValue, fontWeight: 700, fontSize: FONT_SIZE_VALUE },
  metricLabel: { color: COLORS.textMuted, fontSize: FONT_SIZE_CAPTION, marginTop: SPACING_2XS },
  actionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))',
    gap: SPACING_CONTROL_Y,
  },
  actionAllowed: {
    border: `1px solid ${COLORS.successBorder}`,
    color: COLORS.successText,
    borderRadius: BORDER_RADIUS_SMALL,
    padding: SPACING_CONTROL_Y,
    background: COLORS.successBg,
    textAlign: 'center',
  },
  actionBlocked: {
    border: `1px solid ${COLORS.blockedBorder}`,
    color: COLORS.blockedSubtleText,
    borderRadius: BORDER_RADIUS_SMALL,
    padding: SPACING_CONTROL_Y,
    background: COLORS.blockedSubtleBg,
    textAlign: 'center',
  },
} satisfies Record<StyleKey, CSSProperties>
